### ISSUE TITLE
Menu not opening

### ISSUE THREAD

**Issue by pep021** [GouveiaXS/angelicxs-NPCCrew#1]
Hello i have a problem. I set up the config correctly and when i go to the dealer and press E nothing happens. Only the  text " Press E to spawn npc" appears and thats it. Nh-context menu doesnt open. I use old ESX could that be the problem ? Please i would really appreciate if someone helps me !

**Comment by GouveiaXS** [comment]
This is the **only** branch of nh-context that I support; other nh-context versions will not work:

https://github.com/whooith/nh-context

**Comment by pep021** [comment]
Thank youu! It works i got this branch and eveyrting is fine!
